### ISSUE TITLE
Pull image from a KubernetesJob 

### ISSUE THREAD

**Issue by DreamyKten** [tekumara/orion-demo#3]
Hello,
Is there a way to configure a docker registry with credentials in a `KubernetesJob ` ? I want to pull a image from a private registry.
```
reception_deployment : Deployment = Deployment.build_from_flow(
    name="private-flow",
    flow=main_flow,
    output="deployment-private-flow.yaml",
    description="private-flow",
    version="snapshot",
    work_queue_name="kubernetes",
    infrastructure=KubernetesJob(), 
    infra_overrides=dict(
        image="myprivate-image:latest",
        env={},
        finished_job_ttl=300)
    )
```
I can not pull `myprivate-image`
Do I have to update `service_account` ?

Thank you

**Comment by tekumara** [comment]
I've not done it myself but you'd need to use one of these methods I think:

https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry

**Comment by DreamyKten** [comment]
thank you

**Comment by tekumara** [comment]
Good luck, I'll close this for now, feel free to reopen it if something else comes up!
